/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "co.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
co_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		co_write_in co_write_1_arg;
		co_read_in co_read_1_arg;
		co_unlink_in co_unlink_1_arg;
	} argument;
	union {
		co_write_out co_write_1_res;
		co_read_out co_read_1_res;
		co_unlink_out co_unlink_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case co_write:
		_xdr_argument = (xdrproc_t) xdr_co_write_in;
		_xdr_result = (xdrproc_t) xdr_co_write_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))co_write_1_svc;
		break;

	case co_read:
		_xdr_argument = (xdrproc_t) xdr_co_read_in;
		_xdr_result = (xdrproc_t) xdr_co_read_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))co_read_1_svc;
		break;

	case co_unlink:
		_xdr_argument = (xdrproc_t) xdr_co_unlink_in;
		_xdr_result = (xdrproc_t) xdr_co_unlink_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))co_unlink_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!co_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	
//	daemon(1, 0);
	
	if(storage_init(argc, argv) < 0)
		return -1;	
	
	register SVCXPRT *transp;

	pmap_unset (CO_PROG, CO_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CO_PROG, CO_VERS, co_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CO_PROG, CO_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CO_PROG, CO_VERS, co_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CO_PROG, CO_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
