/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cs.h"

bool_t
xdr_dnfs_stat (XDR *xdrs, dnfs_stat *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, &objp->s_ino))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->s_mode))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->s_chunks))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->s_copies))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->s_nlink))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->s_uid))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->s_gid))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->s_rdev))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->s_size))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->s_blocks))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->s_atime))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->s_mtime))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->s_ctime))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chunk_info (XDR *xdrs, chunk_info *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, &objp->ip))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->bip))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dnfs_dir (XDR *xdrs, dnfs_dir *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_uint64_t (xdrs, &objp->d_ino))
		 return FALSE;
	 if (!xdr_uint8_t (xdrs, &objp->d_type))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->d_name, PATH_BUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_getattr_in (XDR *xdrs, cs_getattr_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_getattr_out (XDR *xdrs, cs_getattr_out *objp)
{
	register int32_t *buf;

	 if (!xdr_dnfs_stat (xdrs, &objp->st))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_access_in (XDR *xdrs, cs_access_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_access_out (XDR *xdrs, cs_access_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_mkdir_in (XDR *xdrs, cs_mkdir_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_mkdir_out (XDR *xdrs, cs_mkdir_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_rmdir_in (XDR *xdrs, cs_rmdir_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_rmdir_out (XDR *xdrs, cs_rmdir_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_readdir_in (XDR *xdrs, cs_readdir_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->dp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_readdir_out (XDR *xdrs, cs_readdir_out *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->dirs.dirs_val, (u_int *) &objp->dirs.dirs_len, DIR_BUF,
		sizeof (dnfs_dir), (xdrproc_t) xdr_dnfs_dir))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->dp))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_mknod_in (XDR *xdrs, cs_mknod_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_mknod_out (XDR *xdrs, cs_mknod_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_setwflag_in (XDR *xdrs, cs_setwflag_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->promote))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_setwflag_out (XDR *xdrs, cs_setwflag_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_open_in (XDR *xdrs, cs_open_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_open_out (XDR *xdrs, cs_open_out *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, &objp->ino))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->chunks.chunks_val, (u_int *) &objp->chunks.chunks_len, CHUNK_BUF,
		sizeof (chunk_info), (xdrproc_t) xdr_chunk_info))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_newchunk_in (XDR *xdrs, cs_newchunk_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_newchunk_out (XDR *xdrs, cs_newchunk_out *objp)
{
	register int32_t *buf;

	 if (!xdr_chunk_info (xdrs, &objp->chunk))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_release_in (XDR *xdrs, cs_release_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_release_out (XDR *xdrs, cs_release_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_truncate_in (XDR *xdrs, cs_truncate_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_truncate_out (XDR *xdrs, cs_truncate_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_getlist_in (XDR *xdrs, cs_getlist_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_getlist_out (XDR *xdrs, cs_getlist_out *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, &objp->ino))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->chunks.chunks_val, (u_int *) &objp->chunks.chunks_len, CHUNK_BUF,
		sizeof (chunk_info), (xdrproc_t) xdr_chunk_info))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_unlink_in (XDR *xdrs, cs_unlink_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_unlink_out (XDR *xdrs, cs_unlink_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_chown_in (XDR *xdrs, cs_chown_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->owner))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->group))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_chown_out (XDR *xdrs, cs_chown_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_chmod_in (XDR *xdrs, cs_chmod_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_chmod_out (XDR *xdrs, cs_chmod_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_statfs_in (XDR *xdrs, cs_statfs_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, PATH_BUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_statfs_out (XDR *xdrs, cs_statfs_out *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, &objp->f_blocks))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->f_bavail))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->f_bsize))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_auth_in (XDR *xdrs, cs_auth_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, AUTH_BUF))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->passwd, AUTH_BUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cs_auth_out (XDR *xdrs, cs_auth_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_os_heart_in (XDR *xdrs, os_heart_in *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, &objp->total))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->avail))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_os_heart_out (XDR *xdrs, os_heart_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}
