/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "co.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
co_write_1(co_write_in *argp, co_write_out *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, co_write,
		(xdrproc_t) xdr_co_write_in, (caddr_t) argp,
		(xdrproc_t) xdr_co_write_out, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
co_read_1(co_read_in *argp, co_read_out *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, co_read,
		(xdrproc_t) xdr_co_read_in, (caddr_t) argp,
		(xdrproc_t) xdr_co_read_out, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
co_unlink_1(co_unlink_in *argp, co_unlink_out *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, co_unlink,
		(xdrproc_t) xdr_co_unlink_in, (caddr_t) argp,
		(xdrproc_t) xdr_co_unlink_out, (caddr_t) clnt_res,
		TIMEOUT));
}
