/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
cs_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		cs_getattr_in cs_getattr_1_arg;
		cs_access_in cs_access_1_arg;
		cs_mkdir_in cs_mkdir_1_arg;
		cs_rmdir_in cs_rmdir_1_arg;
		cs_readdir_in cs_readdir_1_arg;
		cs_mknod_in cs_mknod_1_arg;
		cs_open_in cs_open_1_arg;
		cs_newchunk_in cs_newchunk_1_arg;
		cs_release_in cs_release_1_arg;
		cs_unlink_in cs_unlink_1_arg;
		cs_truncate_in cs_truncate_1_arg;
		cs_chown_in cs_chown_1_arg;
		cs_chmod_in cs_chmod_1_arg;
		cs_statfs_in cs_statfs_1_arg;
		cs_getlist_in cs_getlist_1_arg;
		cs_setwflag_in cs_setwflag_1_arg;
		cs_auth_in cs_auth_1_arg;
	} argument;
	union {
		cs_getattr_out cs_getattr_1_res;
		cs_access_out cs_access_1_res;
		cs_mkdir_out cs_mkdir_1_res;
		cs_rmdir_out cs_rmdir_1_res;
		cs_readdir_out cs_readdir_1_res;
		cs_mknod_out cs_mknod_1_res;
		cs_open_out cs_open_1_res;
		cs_newchunk_out cs_newchunk_1_res;
		cs_release_out cs_release_1_res;
		cs_unlink_out cs_unlink_1_res;
		cs_truncate_out cs_truncate_1_res;
		cs_chown_out cs_chown_1_res;
		cs_chmod_out cs_chmod_1_res;
		cs_statfs_out cs_statfs_1_res;
		cs_getlist_out cs_getlist_1_res;
		cs_setwflag_out cs_setwflag_1_res;
		cs_auth_out cs_auth_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case cs_getattr:
		_xdr_argument = (xdrproc_t) xdr_cs_getattr_in;
		_xdr_result = (xdrproc_t) xdr_cs_getattr_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_getattr_1_svc;
		break;

	case cs_access:
		_xdr_argument = (xdrproc_t) xdr_cs_access_in;
		_xdr_result = (xdrproc_t) xdr_cs_access_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_access_1_svc;
		break;

	case cs_mkdir:
		_xdr_argument = (xdrproc_t) xdr_cs_mkdir_in;
		_xdr_result = (xdrproc_t) xdr_cs_mkdir_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_mkdir_1_svc;
		break;

	case cs_rmdir:
		_xdr_argument = (xdrproc_t) xdr_cs_rmdir_in;
		_xdr_result = (xdrproc_t) xdr_cs_rmdir_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_rmdir_1_svc;
		break;

	case cs_readdir:
		_xdr_argument = (xdrproc_t) xdr_cs_readdir_in;
		_xdr_result = (xdrproc_t) xdr_cs_readdir_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_readdir_1_svc;
		break;

	case cs_mknod:
		_xdr_argument = (xdrproc_t) xdr_cs_mknod_in;
		_xdr_result = (xdrproc_t) xdr_cs_mknod_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_mknod_1_svc;
		break;

	case cs_open:
		_xdr_argument = (xdrproc_t) xdr_cs_open_in;
		_xdr_result = (xdrproc_t) xdr_cs_open_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_open_1_svc;
		break;

	case cs_newchunk:
		_xdr_argument = (xdrproc_t) xdr_cs_newchunk_in;
		_xdr_result = (xdrproc_t) xdr_cs_newchunk_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_newchunk_1_svc;
		break;

	case cs_release:
		_xdr_argument = (xdrproc_t) xdr_cs_release_in;
		_xdr_result = (xdrproc_t) xdr_cs_release_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_release_1_svc;
		break;

	case cs_unlink:
		_xdr_argument = (xdrproc_t) xdr_cs_unlink_in;
		_xdr_result = (xdrproc_t) xdr_cs_unlink_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_unlink_1_svc;
		break;

	case cs_truncate:
		_xdr_argument = (xdrproc_t) xdr_cs_truncate_in;
		_xdr_result = (xdrproc_t) xdr_cs_truncate_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_truncate_1_svc;
		break;

	case cs_chown:
		_xdr_argument = (xdrproc_t) xdr_cs_chown_in;
		_xdr_result = (xdrproc_t) xdr_cs_chown_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_chown_1_svc;
		break;

	case cs_chmod:
		_xdr_argument = (xdrproc_t) xdr_cs_chmod_in;
		_xdr_result = (xdrproc_t) xdr_cs_chmod_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_chmod_1_svc;
		break;

	case cs_statfs:
		_xdr_argument = (xdrproc_t) xdr_cs_statfs_in;
		_xdr_result = (xdrproc_t) xdr_cs_statfs_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_statfs_1_svc;
		break;

	case cs_getlist:
		_xdr_argument = (xdrproc_t) xdr_cs_getlist_in;
		_xdr_result = (xdrproc_t) xdr_cs_getlist_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_getlist_1_svc;
		break;

	case cs_setwflag:
		_xdr_argument = (xdrproc_t) xdr_cs_setwflag_in;
		_xdr_result = (xdrproc_t) xdr_cs_setwflag_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_setwflag_1_svc;
		break;

	case cs_auth:
		_xdr_argument = (xdrproc_t) xdr_cs_auth_in;
		_xdr_result = (xdrproc_t) xdr_cs_auth_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cs_auth_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!cs_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

static void
os_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		os_heart_in os_heart_1_arg;
	} argument;
	union {
		os_heart_out os_heart_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case os_heart:
		_xdr_argument = (xdrproc_t) xdr_os_heart_in;
		_xdr_result = (xdrproc_t) xdr_os_heart_out;
		local = (bool_t (*) (char *, void *,  struct svc_req *))os_heart_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!os_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	
//	daemon(1, 0);
	
	if(server_init(argc, argv) < 0)
		return -1;
	
	register SVCXPRT *transp;

	pmap_unset (CS_PROG, CS_VERS);
	pmap_unset (OS_PROG, OS_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CS_PROG, CS_VERS, cs_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CS_PROG, CS_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, OS_PROG, OS_VERS, os_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (OS_PROG, OS_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CS_PROG, CS_VERS, cs_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CS_PROG, CS_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, OS_PROG, OS_VERS, os_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OS_PROG, OS_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
